### PR TITLE
Day 4 - 9 cheatsheets plus bonus guides

### PR DESCRIPTION
**Pull request by cansavvy**
Here I'm adding cheatsheets for 4 -6 days as well as two other guides that are in the `resources` folder and I can add a link to on the main page. 

[About good practices](https://github.com/jhudsl/intro_to_R_class/blob/cansavvy/cheatsheets/resources/good-scientific-coding-practices.pdf) 
[Debugging tips!](https://github.com/jhudsl/intro_to_R_class/blob/cansavvy/cheatsheets/resources/debugging_guide.pdf)

### CODE REVIEW

**Comment by cansavvy** [comment]
Hi! All the cheatsheets are added in this PR. I re-rendered the syllabus, but can you make sure it all looks okay? @carriewright11 or @avahoffman ?

**Comment by carriewright11** [comment]
Looks good! Thank you so much for your help with this. We might be missing this image: screenshots/r_search_bar.png

**Comment by cansavvy** [comment]
Ah yes. I'll fetch that

**Comment by avahoffman** [comment]
Made a few tweaks and rebuilt the syllabus - you should be good to merge now (assuming I didn't remove anything important)! Thanks for doing this!!

**Review by avahoffman — APPROVED** [review]
Cleaned up the table a bit and resolved conflicts. Looks awesome otherwise!

**Pull request merged**
