### PR TITLE
Fix broken urls on cheatsheet column

### PR DESCRIPTION
**Pull request by cansavvy**
I noticed some of the urls were broken. Whoops. Fixing them here. I re-made the syllabus files using `make syllabus_files`

### CODE REVIEW

**Comment by cansavvy** [comment]
I'm confused as to why this doesn't yet show up on the class page even though github pages says its built successfully. https://jhudatascience.org/intro_to_R_class/

**Comment by carriewright11** [comment]
Might need to rerender the main index file

**Comment by carriewright11** [comment]
also github has been slow for me today for updating pages

**Comment by cansavvy** [comment]
> Might need to rerender the main index file

How do I do this?

**Comment by cansavvy** [comment]
Figured it out

**Pull request merged**
